name: Azure Static Web Apps CI/CD

# Triggers for main branch and pull requests
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_static_web_app:
    runs-on: ubuntu-latest
    name: Build and Deploy Static Web App
    # Condition to check if it's a push event or a non-closed pull request event.
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    
    steps:
      # Checkout the repository content.
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true
      
      # Build and deploy the static web app.
      - name: Build and Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DELIGHTFUL_WAVE_056CDEA10 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # For GitHub integrations (e.g., PR comments)
          action: "upload"
          app_location: "/"       # App source code path
          api_location: ""        # API source code path (optional)
          output_location: "/"    # Directory for built app content

  close_stale_pr_deployments:
    runs-on: ubuntu-latest
    name: Close Stale PR Deployments
    # Condition to check if it's a closed pull request event.
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    
    steps:
      # Close the pull request.
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DELIGHTFUL_WAVE_056CDEA10 }}
          action: "close"
